# Pre-commit configuration for Konexion project
# This file configures hooks for both frontend and backend

repos:
  # General hooks for all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python backend hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the linter
      - id: ruff
        name: ruff lint (backend)
        files: ^konexion_backend/.*\.py$
        args: [--fix]
      # Run the formatter
      - id: ruff-format
        name: ruff format (backend)
        files: ^konexion_backend/.*\.py$

  # Import sorting for Python
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (backend)
        files: ^konexion_backend/.*\.py$
        args: [--profile, black, --line-length, "120"]

  # Type checking for Python (development mode - less strict)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        name: mypy (backend)
        files: ^konexion_backend/.*\.py$
        additional_dependencies:
          - types-requests
          - pydantic
          - fastapi
        args:
          - --ignore-missing-imports
          - --no-strict-optional
          - --disable-error-code=no-untyped-def
          - --disable-error-code=no-untyped-call

  # Frontend hooks - Local prettier for formatting
  - repo: local
    hooks:
      - id: prettier-frontend
        name: prettier (frontend)
        entry: bash -c 'cd konexion_frontend && npm run format'
        language: system
        files: ^konexion_frontend/.*\.(js|ts|svelte|json|css|md|html)$
        exclude: ^konexion_frontend/(node_modules/|\.svelte-kit/|build/)
        pass_filenames: false

  # Frontend hooks - ESLint for linting
  - repo: local
    hooks:
      - id: eslint-frontend
        name: eslint (frontend)
        entry: bash -c 'cd konexion_frontend && npm run lint'
        language: system
        files: ^konexion_frontend/.*\.(js|ts|svelte)$
        exclude: ^konexion_frontend/(node_modules/|\.svelte-kit/|build/)
        pass_filenames: false

  # Security scanning for Python
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit security scan (backend)
        files: ^konexion_backend/.*\.py$
        args: [-c, bandit.yaml]
        exclude: ^konexion_backend/(__pycache__/|\.venv/)

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        args: [-c, .yamllint.yaml]

# Global configuration
fail_fast: false
